'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Download,FileText,Fingerprint,ImagePlus,Layers3,LoaderCircle,ScanLine,Settings2,ShieldCheck,Sparkles,X} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {registerCardTools} from '@/lib/webmcp';
type Line={text:string;confidence:number|null};
type Job={id:string;status:string;result?:{raw_ocr?:Line[];report?:string};error?:string};
const engines=[{value:'openai',label:'OpenAI Agents',note:'Specialist agents with web search'},{value:'pydantic',label:'Pydantic AI',note:'Typed agent workflow'},{value:'crewai',label:'CrewAI',note:'Coordinated research crew'},{value:'langgraph',label:'LangGraph',note:'Graph-based research workflow'}];
export default function Home(){
 const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[lines,setLines]=useState<Line[]>([]),[engine,setEngine]=useState('openai'),[report,setReport]=useState(''),[reportEngine,setReportEngine]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[token,setToken]=useState(''),[connected,setConnected]=useState(false),[settings,setSettings]=useState(false),[drag,setDrag]=useState(false),[tab,setTab]=useState('report');
 const input=useRef<HTMLInputElement>(null),stop=useRef<AbortController|null>(null);
 const url='';
 const stateRef=useRef({lines,engine,report,busy});
 stateRef.current={lines,engine,report,busy};
 useEffect(()=>registerCardTools(()=>stateRef.current),[]);
 useEffect(()=>()=>stop.current?.abort(),[]);
 useEffect(()=>{if(!file){setPreview('');return;}const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u);},[file]);
 function choose(next?:File){if(!next||busy)return;if(!['image/jpeg','image/png','image/webp'].includes(next.type)){setError('Choose a JPG, PNG, or WebP image.');return;}if(next.size>10*1024*1024){setError('Choose an image smaller than 10 MB.');return;}setFile(next);setLines([]);setReport('');setError('');}
 async function request(path:string,options:RequestInit={},signal?:AbortSignal){const response=await fetch(url+path,{...options,signal,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...options.headers}});const data=await response.json() as Job & {detail?:string};if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:data.error||'The request could not be completed.');return data;}
 async function connect(){setError('');try{if(!token.trim())throw new Error('Enter your backend access token.');await request('/health',{},AbortSignal.timeout(12000));setConnected(true);setSettings(false);}catch(e){setConnected(false);setError(e instanceof TypeError?'Could not reach the research service. Please try again.':(e as Error).message);}}
 async function run(kind:'ocr'|'research'){
  if(!connected){setSettings(true);setError('Enter your access token to unlock OCR and research.');return;}
  setError('');setBusy(kind);const controller=new AbortController();stop.current=controller;
  try{let payload:Record<string,unknown>={engine,lines};if(kind==='ocr'){if(!file)throw new Error('Upload a card first.');const image=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});payload={image};}
   const {id}=await request('/jobs/'+kind,{method:'POST',body:JSON.stringify(payload)},controller.signal);
   let job:Job;do{await new Promise<void>((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Stopped','AbortError'));};const timer=setTimeout(()=>{controller.signal.removeEventListener('abort',abort);resolve();},1500);controller.signal.addEventListener('abort',abort,{once:true});});job=await request('/jobs/'+id,{},controller.signal);}while(job.status==='queued'||job.status==='running');
   if(job.status!=='succeeded')throw new Error(job.error||'The job failed. Try again.');
   if(kind==='ocr'){setLines(job.result?.raw_ocr||[]);setReport('');setTab('ocr');if(!job.result?.raw_ocr?.length)setError('No label text detected. Try a clearer, tightly framed card image.');}else{setReport(job.result?.report||'No report was returned.');setReportEngine(engines.find(e=>e.value===engine)?.label||engine);setTab('report');}
  }catch(e){if((e as Error).name!=='AbortError')setError(e instanceof TypeError?'Connection lost. Check that the Python backend is running.':(e as Error).message);}finally{setBusy('');stop.current=null;}
 }
 function download(){const u=URL.createObjectURL(new Blob([JSON.stringify({engine:reportEngine,raw_ocr:lines,report},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='card-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 const scores=lines.filter(l=>l.confidence!==null),average=scores.length?scores.reduce((s,l)=>s+(l.confidence||0),0)/scores.length:null;
 return <div className="app-shell">
  <header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Layers3 size={23}/></span>CARD<span className="brand-light">LAB</span></a><span className="header-caption">THE COLLECTOR’S RESEARCH DESK</span><button className="connection" onClick={()=>setSettings(!settings)} disabled={!!busy}><span className={connected?'status-dot online':'status-dot'}/>{connected?'Workspace unlocked':'Unlock workspace'}<Settings2 size={15}/></button></header>
  <main><div className="page-heading"><div><div className="eyebrow">CARD INTELLIGENCE</div><h1>Every card has a story.<br/><span>Research yours.</span></h1><p>Read the label. Research the player. Understand the market.</p></div><div className="desk-mark"><ScanLine size={22}/><span>From slab to insight</span></div></div>
  {settings&&<section className="settings-panel"><h2>Unlock your research workspace</h2><p>Enter your access token to use OCR and research. The token stays in this tab.</p><div className="connection-fields"><label>Access token<input type="password" value={token} onChange={e=>{setToken(e.target.value);setConnected(false);}} autoComplete="off"/></label><button className="primary small" onClick={connect}>Unlock<ArrowRight size={16}/></button></div></section>}
  {error&&<div role="alert" className="error-box">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={17}/></button></div>}
  <div className="workspace"><section className="input-panel">
   <div className="section-heading"><span className="step-number">01</span><h2>Your card</h2><span className="mini-label">JPG · PNG · WEBP</span></div>
   <input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={!!busy} onChange={e=>choose(e.target.files?.[0])}/>
   <button className={'upload-zone '+(drag?'dragging ':'')+(preview?'has-image':'')} disabled={!!busy} onClick={()=>input.current?.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0]);}}>
   {preview?<><img src={preview} alt="Uploaded sports card"/><span className="replace-image">Replace image</span></>:<><span className="upload-icon"><ImagePlus size={30} strokeWidth={1.5}/></span><strong>Drop your card here</strong><span>or click to choose an image</span><small>Up to 10 MB</small></>}</button>
   <div className="photo-tip"><ScanLine size={18}/><p>Keep the grading label at the top of the image, sharp and fully visible.</p></div>{file&&<p className="filename">{file.name}</p>}
   <button className="secondary full" disabled={!file||!!busy} onClick={()=>run('ocr')}>{busy==='ocr'?<LoaderCircle className="spin" size={17}/>:<ScanLine size={17}/>} {busy==='ocr'?'Reading card label…':'Read card label'}<ArrowRight size={17}/></button>
   <div className="engine-section"><div className="section-heading"><span className="step-number">02</span><h2>Research engine</h2></div><Select value={engine} onValueChange={v=>v&&setEngine(v)} disabled={!!busy}><SelectTrigger className="engine-select" aria-label="Research engine"><SelectValue>{engines.find(e=>e.value===engine)?.label}</SelectValue></SelectTrigger><SelectContent>{engines.map(e=><SelectItem value={e.value} key={e.value}>{e.label}</SelectItem>)}</SelectContent></Select><p className="engine-note">{engines.find(e=>e.value===engine)?.note}</p>
   <button className="primary full" disabled={!lines.some(l=>l.text.trim())||!!busy} onClick={()=>run('research')}>{busy==='research'?<LoaderCircle className="spin" size={18}/>:<Sparkles size={18}/>} {busy==='research'?'Researching card…':'Research card'}<ArrowRight size={18}/></button><p className="research-note">Card identification, market evidence & player research</p></div>
  </section>
  <section className="report-panel"><div className="report-header"><div className="section-heading"><span className="step-number">03</span><h2>Research report</h2></div><button className="download" disabled={!report||!!busy} onClick={download}><Download size={16}/><span>Export JSON</span></button></div>
   <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList variant="line" className="report-tabs"><TabsTrigger value="report">Overview</TabsTrigger><TabsTrigger value="ocr">Label text {lines.length>0&&<span className="count">{lines.length}</span>}</TabsTrigger></TabsList>
   <TabsContent value="report">{report?<div className="report-content"><div className="report-meta"><span><Check size={14}/> Research complete</span><span>{reportEngine}</span></div><div className="report-text">{report}</div></div>:<div className="report-empty"><span className="empty-icon"><Fingerprint size={40} strokeWidth={1.1}/></span><div className="eyebrow">{busy==='research'?'RESEARCH IN PROGRESS':'YOUR NEXT DISCOVERY STARTS HERE'}</div><h3>{busy==='research'?'Following the evidence.':'A clearer picture of your card.'}</h3><p>{busy==='research'?'Your agents are checking the card, researching market evidence, and gathering player information. This can take several minutes.':'Upload a graded sports card and read its label to start a source-backed research report.'}</p><div className="report-topics"><div><span>01</span><strong>Card identity</strong><small>Set, grade & certification</small></div><div><span>02</span><strong>Market evidence</strong><small>Sales, value & outlook</small></div><div><span>03</span><strong>Player profile</strong><small>Career & accomplishments</small></div></div></div>}</TabsContent>
   <TabsContent value="ocr"><div className="ocr-content"><div className="ocr-heading"><h3>Review the label</h3>{average!==null&&<span>{(average*100).toFixed(1)}% confidence</span>}</div><p>Check the extracted text before running research. Correct any characters the reader missed.</p>{lines.length?lines.map((line,i)=><div className="ocr-line" key={i}><span>{String(i+1).padStart(2,'0')}</span><input aria-label={`Label line ${i+1}`} value={line.text} disabled={!!busy} onChange={e=>{setLines(lines.map((l,j)=>j===i?{text:e.target.value,confidence:null}:l));setReport('');}}/><small>{line.confidence===null?'Edited':`${Math.round(line.confidence*100)}%`}</small></div>):<div className="label-empty"><FileText size={28}/><p>Read a card image to see its label text here.</p></div>}</div></TabsContent></Tabs>
   <div className="evidence-note"><ShieldCheck size={18}/><p>Research favors confirmed sales over asking prices. Unverified information should be identified in the report.</p></div>
  </section></div><footer><span><Layers3 size={15}/> CARD LAB</span><span>Built around your AI Agent workflow</span><span>Upload → Read → Research</span></footer></main></div>;
}
